{% set name = "allennlp" %}
{% set version = "0.9.0" %}

{% set spacy_model = "en_core_web_sm" %}
{% set spacy_model_version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: {{ name }}
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: f70a2d83146630bcc213ed64ff868e3fed8519480fb495dee14a8a5b19c2ff90

  # Spacy Model
  - folder: {{ spacy_model }}
    url: https://github.com/explosion/spacy-models/releases/download/{{ spacy_model }}-{{ spacy_model_version }}/{{ spacy_model }}-{{ spacy_model_version }}.tar.gz
    sha256: 9d9d231d7c9cbad82178b566fdb25768e3d5098af23ce11e03ec4f432f4a2298

build:
  entry_points:
    - allennlp=allennlp.run:run
  number: 0
  script: "{{ PYTHON }} -m pip install ./{{ name }} --no-deps -vv"
  skip: True  # [not linux or py<36]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - jsonnet >=0.10.0
    - overrides
    - nltk
    - spacy
    - numpy
    - tensorboardX >=1.2
    - boto3
    - flask >=1.0.2
    - flask-cors >=3.0.7
    - gevent >=1.3.6
    - requests >=2.18
    - tqdm >=4.19
    - editdistance
    - h5py
    - scikit-learn
    - scipy
    - pytz >=2017.3
    - unidecode
    - matplotlib >=2.2.3
    - pytest
    - flaky
    - responses >=0.7
    - numpydoc >=0.8.0
    - conllu ==1.3.1
    - parsimonious >=0.8.0
    - ftfy
    - sqlparse >=0.2.4
    - word2number >=1.1
    - jsonpickle
    - pytorch
    - pytorch >=1.2.0
    - pytorch-pretrained-bert >=0.6.0
    - cudatoolkit

test:
  source_files:
    - {{ spacy_model }}
  commands:
    - python -m spacy link {{ spacy_model }}/{{ spacy_model }} {{ spacy_model }}
    - allennlp test-install
  imports:
    - allennlp
    - allennlp.commands
    - allennlp.data
    - allennlp.models
    - allennlp.modules
    - allennlp.nn
    - allennlp.service
    - allennlp.training

  requires:
    - ipykernel <5.0.0
    - jupyter
    - nltk_data

about:
  home: https://allennlp.org/
  license: Apache-2.0
  license_family: APACHE
  license_file: {{ name }}/LICENSE
  summary: An open-source NLP research library, built on PyTorch.
  description: |
    An Apache 2.0 NLP research library, built on PyTorch, for developing state-of-the-art
    deep learning models on a wide variety of linguistic tasks.
  doc_url: https://allenai.github.io/allennlp-docs/
  dev_url: https://github.com/allenai/allennlp

extra:
  recipe-maintainers:
    - CurtLH
    - sodre
